const tags = [
    { id: "1", name: "New" },
    { id: "2", name: "Lightly Used" },
    { id: "3", name: "Used" },
    { id: "4", name: "Spring" },
    { id: "5", name: "Summer" },
    { id: "6", name: "Fall" },
    { id: "7", name: "Winter" },
    { id: "8", name: "Mens" }, 
    { id: "9", name: "Womens" },
    { id: "10", name: "Unisex" },
    { id: "11", name: "Casual Wear" },
    { id: "12", name: "Formal Wear" },
    { id: "13", name: "Plus Size" },
    { id: "14", name: "Street Wear" },
    { id: "15", name: "Sports Wear" },
    { id: "16", name: "Fitness and Sports Equipment" },
    { id: "17", name: "Handmade" },
    { id: "18", name: "Gift" },
    { id: "19", name: "Vintage" },
    { id: "20", name: "Brown Merchandise" }, 
    { id: "21", name: "Holiday" },
    { id: "22", name: "Daily Essentials" },
    { id: "23", name: "School Essentials" },
    { id: "24", name: "Beauty products" },
    { id: "25", name: "Eco-friendly" },
    { id: "26", name: "Cruelty-free" },
    { id: "27", name: "Vegan" },
    { id: "28", name: "BIPOC-made" },
    { id: "29", name: "Cute" },
    { id: "30", name: "Cultural" },
    { id: "31", name: "Artsy" },
    { id: "32", name: "Custom" }
  ];

export default tags